devices/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^(?P<network_name>[a-zA-Z0-9_ ]+)/$',
        views.network_details, name='network_details'),

    url(r'^(?P<network_name>[a-zA-Z0-9_ ]+)/(?P<node_name>[a-zA-Z0-9_ ]+)/$',
        views.node_details, name='node_details'),


]

iotm/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^devices/', include('devices.urls', namespace="devices")),
]

account/models.py
from django.db import models

class Organization(models.Model):
	name = models.CharField(max_length=45)

class User(models.Model):
	name = models.CharField(max_length=45)
	organization = models.ManyToManyField(Organization)
	email = models.EmailField()

devices/models.py
from django.db import models
from django.core.validators import ValidationError, MinLengthValidator
"""Abstracts"""


class DisplayName(models.Model):
    name = models.SlugField(max_length=45, validators=[MinLengthValidator(1)])

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class TimingData(models.Model):
    created = models.DateTimeField('created', auto_now_add=True)
    last_modified = models.DateTimeField('last modified', auto_now=True)

    class Meta:
        abstract = True
"""End Abstracts"""


class Organization(TimingData, DisplayName):
    # this is a placeholder
    pass


class Network(TimingData, DisplayName):
    owner = models.ForeignKey(Organization)

    def validate_unique(self, *args, **kwargs):
        super(Network, self).validate_unique(*args, **kwargs)

        old_network = self.__class__.objects.filter(
            name=self.name, owner=self.owner.pk)

        if old_network.exists():
            raise ValidationError("Network with that name already exists")


class Node(TimingData, DisplayName):
    network = models.ForeignKey(Network)


class SensorType(TimingData, DisplayName):
    manufacturer = models.CharField(max_length=45)
    units = models.CharField(max_length=10)


class Sensor(TimingData, DisplayName):
    node = models.ForeignKey(Node)
    model = models.ForeignKey(SensorType)


class ActuatorType(TimingData, DisplayName):
    manufacturer = models.CharField(max_length=45)


class Actuator(TimingData, DisplayName):
    node = models.ForeignKey(Node)
    model = models.ForeignKey(ActuatorType)


class SensorData(TimingData):
    value = models.IntegerField()
    sensor = models.ForeignKey(Sensor)


class ActuatorData(TimingData):
    value = models.IntegerField()
    actuator = models.ForeignKey(Actuator)

account/views.py
from django.shortcuts import render

# Create your views here.

devices/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Network, Node, Organization
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError


def index(request):
    error = ''
    if (request.POST and 'new_network_name' in request.POST):
        new_network_name = request.POST['new_network_name']

        network = Network()
        network.name = new_network_name

        # TODO: add a real organization getter
        network.owner = Organization.objects.get()

        # if validation errors, don't save, render the same page but send
        # the errors to the template
        try:
            network.full_clean()
        except ValidationError as e:
            error = e
        else:
            network.save()
            return HttpResponseRedirect(reverse('devices:index'))

    network_list = Network.objects.order_by()

    context = {
        'network_list': network_list,
        'error': error
    }

    return render(request, 'devices/index.html', context)


def network_details(request, network_name):
    network = get_object_or_404(Network, name=network_name)

    return render(
        request,
        'devices/network_details.html',
        {'network': network}
    )


def node_details(request, network_name, node_name):
    node = get_object_or_404(Node, name=node_name)
    return render(request, 'devices/node_details.html', {'node': node})

devices/templates/devices/index.html
<h1>My Network Listing:</h1>
{% if network_list %}
    <ul>
    {% for network in network_list %}
        <li><a href="{% url 'devices:network_details' network.name %}">{{ network.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Networks are available.</p>
{% endif %}

<p>
    Add a Network:
    <form action="{% url 'devices:index' %}" method="post">
        {% csrf_token %}
        <label for="network_name">Name: </label>
        <input type="text" name="new_network_name" id="new_network_name" />
        <input type="submit" value="Create" />
    </form>
</p>

{% if error %}
    {% for message in error.messages %}
        <ul>
            {{ message }}
        </ul>
    {% endfor %}
{% endif %}

devices/templates/devices/network_details.html
<h1>Network Info:</h1>
<h2>{{network}}</h2>
<h2>Nodes:</h2>
<ul>
{% for node in network.node_set.all %}
    <li><a href="{% url 'devices:node_details' network.name node.name %}">{{ node.name }}</a></li>
{% endfor %}
</ul>

devices/templates/devices/node_details.html
<h1>Node Info:</h1>
<h2>{{ node }}</h2>
<h2>Sensors</h2>
<ul>
    {% for sensor in node.sensor_set.all %}
        <li>{{ sensor.model }} : {{ sensor.model.manufacturer}}</li>
    {% endfor %}
</ul>

<h2>Actuators</h2>
<ul>
    {% for actuator in node.actuator_set.all %}
        <li>{{ actuator.model }} : {{ actuator.model.manufacturer}}</li>
    {% endfor %}
</ul>